### ISSUE TITLE
docker compose not working on win7

### ISSUE THREAD

**Issue by dmatejka** [DanWahlin/Angular-RESTfulService#10]
Strugling with making it work with docker-compose. 
using Docker toolbox on win7, docker 1.13

Nodeapp is exiting. I think the problem is because VOLUME puts in node-modules from WIN-nodejs which doesnt work in container. 

Should be npm install in nodeapp dockerfile and move server.js and PUBLIC to some DEV folder to set it as the VOLUME 

Daniel

**Comment by DanWahlin** [comment]
It's working correctly on my Windows and Mac machines so assuming you've followed all of the steps in the readme I'd make sure that you're running the code from within the /Users folder (try putting it on your desktop to start) since otherwise the volume won't be able to work correctly. That's something Docker Toolbox requires.

**Comment by dmatejka** [comment]
oooh... my lord! .. I am so dumb.. wasted few hours trying to run it from d:\\ ..  
THANK YOU Dan! really appriciate your time.

**Comment by DanWahlin** [comment]
The good news is you'll probably never forget that one. I did the same thing when I first started with Docker. Easy once you know - painful when you don't know or aren't thinking about it.
