### ISSUE TITLE
[Question] How would I make new requests to the service?

### ISSUE THREAD

**Issue by julianonunes** [DanWahlin/Angular-RESTfulService#11]
Hi Dan,

If I need to make new requests to this.dataService.getCustomersSummary() as the user types a value to filter in a Textbox, do I need to execute the same expression again or will it be different?

```
this.dataService.getCustomersSummary()
            .subscribe((data: ICustomer[]) => this.customers = data);
```

https://github.com/DanWahlin/Angular-RESTfulService/blob/master/app/customers/customers.component.ts

**Comment by DanWahlin** [comment]
Sorry for the delay. I didn't get a notification for this for some reason so I'm just now seeing it. Because Http calls subscribe and then unsubscribe once the response comes back you'll need to call the function that executes the code you mention above again if you want new data. You'd have to make a new one of course that accepts the filter data if you plan on server-side filtering.
