### ISSUE TITLE
seed data is not loaded 

### ISSUE THREAD

**Issue by sankyavi** [DanWahlin/Angular-RESTfulService#4]
I am unable to load the seed data ?

I can see the following 2 lines being printed from config loader :
console.log('Node environment: ' + env);
console.log('loading config.' + env + '.json');

I have mongodb up and running and mongoose installed.
Do i have to create the  customermanager first or something ?.

**Comment by sankyavi** [comment]
I see the following message while running the app.

starting child process with 'node server.js'
crashing child

i am running it via lite server on a different port .

**Comment by DanWahlin** [comment]
As long as you're running the steps listed in the readme the seed data should load automatically. I just tried it on both Mac and Windows and everything worked correctly. Make sure you have the latest version of the code.

**Update:** I just realized you're running it with "lite server". You have to run it with Node since it hits a database. Lite server is only for static files. Please follow the steps show in the readme and it should work properly.
