### ISSUE TITLE
localhost:3000 hangs

### ISSUE THREAD

**Issue by slashbrackets** [DanWahlin/Angular-RESTfulService#8]
Started the site via npm start and it seems to load everything fine and starts the server. However, when I navigate to the site it just spins and never loads in the browser.

**Comment by DanWahlin** [comment]
Hard to say without any additional information. I can confirm it's working on my Mac and Windows machines. I'd check for any errors in the console, ensure that MongoDB is up and running (I'm assuming you must be running locally rather than using the Docker option), ensure that you changed the connection string to "localhost", etc.

**Comment by danielwallgren** [comment]
@DanWahlin I'm having the same issue as @slashbrackets, keeps trying to load forever.

Console / Network doesn't output anything.

My current versions are:
node v6.7.0
npm 3.10.7
MongoDB shell version: 3.2.10

Do you have any suggestions?

Update:
Just got som info out of my mongoDB server:
-----8<-----
13:39:04.652+0200 I NETWORK  [websvr] Socket recv() errno:10060 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 127.0.0.1:4803
----- / 8<-----

Update2:
The problem seem to be "concurrently" (on windows) since it's working when I'm running these tasks in different bash:
"npm run tsc:w"
"supervisor -i app server.js"

**Comment by DanWahlin** [comment]
Thanks for the extra info there @danielhansson. After playing around with it more on my Windows box I was finally able to hit the issue. It looks like Supervisor running in conjunction with Concurrently is the problem (the odd thing is it still works fine "as is" on my Mac box...I hate when there's differences there). I switched things over to Nodemon and everything seems to be working properly on Windows and on Mac. Nodemon also seems to now work properly with Docker volumes which is good and can successfully detect file changes.

If you get a chance to try out the latest version (go through the readme again) let me know if it works OK on your end. Thanks!

**Comment by danielwallgren** [comment]
Great @DanWahlin !

Works like a charm ;).

**Comment by DanWahlin** [comment]
Great - thanks for checking it out!
